### PR TITLE
Fix issue 26

### PR DESCRIPTION
**Pull request by m4gr3d**
Fixes issue #26: The service is started when the activity starts, and it checks if the GCS is already connected (in case the connection event was missed).

### CODE REVIEW

**Comment by m4gr3d** [comment]
Depends on PR #28.

**Comment by squilter** [comment]
@ne0fhyk Thanks for the help.  Was there any other issue that you found while testing the other day?

**Comment by m4gr3d** [comment]
I had issues with the stability of the app on pebble. Kept crashing, but i'm not familiar enough with that code to pinpoint the issue.

**Comment by squilter** [comment]
ok.  will investigate.

**Pull request merged**
